version: "3.8"

services:
  sql-server-db:
    container_name: "sql-server-db"
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "123456"
        ACCEPT_EULA: "Y"

  mogo-grid-fs:
    container_name: "mongo-grid-fs"
    image: mongo:latest
    ports:
        - "27017:27017"
    volumes:
        - dbdata6:/data/db
        
  redis:
    container_name: "redis"
    image: redis:latest



